---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/apiman/src/main/fabric8/icon.png"
  labels:
    component: "ApimanManagerAPI"
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.ipaas.apps"
  name: "apiman"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: "ApimanManagerAPI"
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.ipaas.apps"
  template:
    metadata:
      labels:
        component: "ApimanManagerAPI"
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.ipaas.apps"
    spec:
      containers:
      - env:
        - name: "AB_JOLOKIA_AUTH_OPENSHIFT"
          value: "true"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/apiman:${project.version}"
        name: "apiman"
        ports:
        - containerPort: 7070
          name: "http"
        - containerPort: 8778
          name: "jolokia"
        readinessProbe:
          httpGet:
            path: "/apiman/"
            port: 7070
          initialDelaySeconds: 15
          timeoutSeconds: 60
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
      serviceAccountName: "fabric8"
