---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    api.service.kubernetes.io/description-language: "SwaggerJSON"
    api.service.kubernetes.io/path: "apiman"
    api.service.kubernetes.io/protocol: "REST"
    api.service.kubernetes.io/description-path: "apiman/swagger.json"
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/apiman/src/main/fabric8/icon.png"
    fabric8.io/app-menu: development
  labels:
    component: "ApimanManagerAPI"
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.ipaas.apps"
  name: "apiman"
spec:
  ports:
  - port: 7070
    protocol: "TCP"
    targetPort: 7070
  selector:
    project: "apiman"
    component: "ApimanManagerAPI"
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
