---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    api.service.kubernetes.io/protocol: "REST"
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/elasticsearch-v1/master/elasticsearch/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.ipaas.apps"
  name: "elasticsearch-v1-masters"
spec:
  clusterIP: "None"
  ports:
  - port: 9300
    protocol: "TCP"
    targetPort: 9300
  selector:
    project: "elasticsearch-v1"
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
  type: "LoadBalancer"
