---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/elasticsearch/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.ipaas.apps"
  name: "elasticsearch-v1"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.ipaas.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.ipaas.apps"
    spec:
      containers:
      - env:
        - name: "SERVICE_DNS"
          value: "elasticsearch-v1-masters"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/elasticsearch-v1:${project.version}"
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 9300
        name: "elasticsearch-v1"
        ports:
        - containerPort: 9200
          name: "http"
        - containerPort: 9300
          name: "transport"
        readinessProbe:
          exec:
            command:
            - "/probe.sh"
            - "http"
          initialDelaySeconds: 30
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: "elasticsearch-data"
          readOnly: false
      volumes:
      - name: "elasticsearch-data"
