---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/kafka/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.ipaas.apps"
  name: "kafka"
spec:
  ports:
  - port: 9092
    protocol: "TCP"
    targetPort: 9092
  selector:
    project: "kafka"
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
  type: "LoadBalancer"
