---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/activemq.svg"
  labels:
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
    project: "message-broker"
    version: "${project.version}"
  name: "message-broker"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      group: "io.fabric8.ipaas.apps"
      project: "message-broker"
  template:
    metadata:
      labels:
        provider: "fabric8"
        group: "io.fabric8.ipaas.apps"
        project: "message-broker"
        version: "${project.version}"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/message-broker:${project.version}"
        name: "message-broker"
        ports:
        - containerPort: 61616
          name: "amq"
        - containerPort: 8778
          name: "jolokia"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
