---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    api.service.kubernetes.io/description-language: "SwaggerJSON"
    api.service.kubernetes.io/path: "api"
    api.service.kubernetes.io/protocol: "REST"
    api.service.kubernetes.io/description-path: "api/swagger.json"
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/apiman-gateway/src/main/fabric8/icon.png"
  labels:
    component: "ApimanGateway"
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.ipaas.apps"
  name: "apiman-gateway"
spec:
  ports:
  - port: 7777
    protocol: "TCP"
    targetPort: 7777
  selector:
    project: "apiman-gateway"
    component: "ApimanGateway"
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
