---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.ipaas.apps"
    serverId: "1"
  name: "zookeeper"
spec:
  replicas: 1
  selector:
    matchLabels:
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "io.fabric8.ipaas.apps"
  template:
    metadata:
      labels:
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "io.fabric8.ipaas.apps"
    spec:
      containers:
      - env:
        - name: "ENSEMBLE_SIZE"
          value: "1"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/zookeeper:${project.version}"
        name: "zookeeper"
        ports:
        - containerPort: 2181
          name: "zkclient"
        - containerPort: 8778
          name: "jolokia"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        volumeMounts:
        - mountPath: "/opt/zookeeper/data"
          name: "data"
          readOnly: false
        - mountPath: "/opt/zookeeper/log"
          name: "log"
          readOnly: false
      volumes:
      - emptyDir:
          medium: "Memory"
        name: "data"
      - emptyDir:
          medium: "Memory"
        name: "log"
