---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-ipaas/master/zookeeper/src/main/fabric8/icon.png"
  labels:
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "io.fabric8.ipaas.apps"
  name: "zookeeper-1"
spec:
  clusterIP: "None"
  ports:
  - name: "election"
    port: 3888
    targetPort: 3888
  - name: "peer"
    port: 2888
    targetPort: 2888
  selector:
    project: "zookeeper"
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
    serverId: "1"
