---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/activemq.svg"
  labels:
    component: "message-broker"
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "messaging"
  name: "jnatsd"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: "message-broker"
      provider: "fabric8"
      project: "${project.artifactId}"
      group: "messaging"
  template:
    metadata:
      labels:
        component: "message-broker"
        provider: "fabric8"
        project: "${project.artifactId}"
        version: "${project.version}"
        group: "messaging"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "fabric8/jnatsd:${project.version}"
        name: "jnatsd"
        ports:
        - containerPort: 61616
          name: "amq"
        - containerPort: 8778
          name: "jolokia"
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
