---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/activemq.svg"
  labels:
    component: "message-broker"
    provider: "fabric8"
    project: "${project.artifactId}"
    version: "${project.version}"
    group: "messaging"
  name: "jnatsd"
spec:
  ports:
  - port: 4222
    protocol: "TCP"
    targetPort: 4222
  selector:
    project: "jnatsd"
    component: "message-broker"
    provider: "fabric8"
    group: "messaging"
