---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/iconUrl: "img/icons/activemq.svg"
  labels:
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
    project: "jnatsd"
  name: "nats"
spec:
  ports:
  - port: 4222
    protocol: "TCP"
    targetPort: 42222
  selector:
    provider: "fabric8"
    group: "io.fabric8.ipaas.apps"
    project: "jnatsd"
